### ISSUE TITLE
License check failure causes pkg.go.dev README limitations

### ISSUE THREAD

**Issue by hrmnjt** [wardn/sortfile#1]
## Issue

License check fail causes the godoc to not being displayed in README section.

## Context

[GoDoc](https://godoc.org/github.com/wardn/data/stream/sort/mergesort) has been migrated to [pkg.go.dev](https://pkg.go.dev/github.com/wardn/data/stream/sort/mergesort) and with this change they have added a [License policy](https://pkg.go.dev/license-policy) and License check.

Due to license check failure, the README section is not displayed. 

![image](https://user-images.githubusercontent.com/10371494/74924571-308aa000-53ec-11ea-8a3a-18cd03d03ca7.png)

**Comment by hrmnjt** [comment]
@wardn Please let me know if you expect a PR and I'll be happy to contribute. Reference: https://choosealicense.com/

**Comment by wardn** [comment]
Added the license, let me know if that fixes the problem for ya
